# Generated by Django 5.2.11 on 2026-03-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('allocatedAnimal', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
